---

# Ensure HA Proxy Installed
- name: "HAPROXY::INSTALL - Ensure HAProxy is installed"
  ansible.builtin.package:
    name: haproxy
    state: present

# Ensure HA Proxy is Enabled
- name: "HAPROXY::INSTALL - Ensure HAProxy enabled (DEBIAN)"
  ansible.builtin.lineinfile:
    dest: /etc/default/haproxy
    regexp: "^ENABLED.+$"
    line: "ENABLED=1"
    state: present
  when: ansible_os_family == 'Debian'

# Get HA Proxy Version
- name: "HAPROXY::INSTALL - Get HAProxy version"
  ansible.builtin.command: haproxy -v
  register: haproxy_version_result
  changed_when: false
  check_mode: false

# Extract HA Proxy Version Number
- name: "HAPROXY::INSTALL - Extract HA Proxy Version Number"
  ansible.builtin.set_fact:
    _haproxy_version: >-
      {{
        haproxy_version_result.stdout_lines[0] | regex_replace("^HA-?Proxy version (\d+(\.\d+)*).*$", "\1")
      }}

# Ensure OS Specific Vars Included
- name: "HAPROXY::INSTALL - Ensure OS Specific Vars Included"
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
        - "vars/none.yml"

# Ensure Dataplane API Installed
- name: "HAPROXY::INSTALL - Ensure Dataplane API Installed"
  ansible.builtin.include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "setup-dataplane-{{ ansible_distribution }}.yml"
        - "setup-dataplane-{{ ansible_os_family }}.yml"
        - "none.yml"

# Ensure HA Proxy Dataplane API Configuration Generated
- name: "HAPROXY::INSTALL - Ensure HA Proxy Dataplane API Configuration Generated"
  ansible.builtin.template:
    src: dataplaneapi.yml.j2
    dest: "{{ _haproxy_dataplane_config_file }}"
    mode: "0644"
  notify: Restart haproxy
  when:
    - haproxy_dataplane.enabled | default(true)

# Ensure HA Proxy Configuration Generated
- name: "HAPROXY::INSTALL - Ensure HA Proxy Configuration Generated"
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: "0644"
    validate: haproxy -f %s -c -q
  vars:
    haproxy_version: "{{ _haproxy_version }}"
  notify: Restart haproxy

# Ensure Handlers Flushed
- name: "HAPROXY::INSTALL - Ensure Handlers Flushed"
  ansible.builtin.meta: flush_handlers

# Ensure HA Proxy Enabled and Started
- name: "HAPROXY::INSTALL - Ensure HA Proxy Restarted"
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: true
