---
- name: "Install plugin from binaries.sonarsource.com"
  include: setup_plugin_binaries.yml
  when: not sonar_cplugin.get('marketplace', false)|bool

- name: "Install plugin from updates.sonarsource.com"
  include: setup_plugin_marketplace.yml
  when: sonar_cplugin.get('marketplace', false)|bool

- name: "Download current plugin [{{ sonar_cplugin.name }}]"
  get_url:
    url: "{{ cplugin_url }}"
    dest: "{{ __sonar_plugin_home }}"
    owner: "{{ sonar_user }}"
    group: "{{ sonar_group }}"
    mode: "0644"
  retries: 5
  delay: 10
  notify:
    - "restart SonarQube service"
