---
- name: "Set current plugin's jar filename [{{ sonar_cplugin.name }}]"
  ansible.builtin.set_fact:
    cplugin_fname: "{{ sonar_cplugin.name }}-{{ sonar_cplugin.version }}.jar"

- name: "Set current plugins's custom download URL if available [{{ sonar_cplugin.name }}]"
  ansible.builtin.set_fact:
    cplugin_url: "{{ sonar_cplugin.url }}"
  when: sonar_cplugin.url is defined and sonar_cplugin.url | length > 0

- name: "Set current plugins's default download URL no custom one [{{ sonar_cplugin.name }}]"
  ansible.builtin.set_fact:
    cplugin_url: "{{ sonar_cplugin.commercial | ternary(sonar_commercial_plugin_baseurl,sonar_plugin_baseurl) }}/{{ sonar_cplugin.name }}/{{ cplugin_fname }}"
  when: cplugin_url is not defined or cplugin_url | length <= 0
