---
galaxy_info:
    author: jetune
    role_name: maven
    description: Maven installation ansible role
    company: "Kube Cloud"
    issue_tracker_url: https://github.com/kube-cloud/ansible-collection-general/issues
    license: "license (Apache 2.0)"
    min_ansible_version: '2.8'
    github_branch: master
    platforms:
        - name: EL
          versions:
              - all
        - name: Debian
          versions:
              - all
        - name: Ubuntu
          versions:
              - all
    galaxy_tags:
        - development
        - java
        - jdk
        - opendjk
        - oracle
        - system
        - linux
        - build
        - maven
dependencies: []
