---
# Install Apache Maven main tasks on Supported system
- name: Install Apache Maven main tasks on Supported system
  block:

    # Include Initialize tasks (Linux)
    - name: Include Initialize tasks
      ansible.builtin.include_tasks: "initialize.yml"

    # Include Download tasks (Linux)
    - name: Include download tasks
      ansible.builtin.include_tasks: "download.yml"

    # Include Setup tasks (Linux)
    - name: Include install tasks
      ansible.builtin.include_tasks: "install.yml"
