---
galaxy_info:
    author: jetune
    role_name: ovh_acme_certificate
    description: Ansible Role for ACME Certificate Management based on OVH DNS Challenge
    company: "Kube Cloud"
    issue_tracker_url: https://github.com/kube-cloud/ansible-collection-general/issues
    license: "license (Apache 2.0)"
    min_ansible_version: "2.9"
    github_branch: master
    platforms:
        - name: EL
          versions:
              - "6"
              - "7"
        - name: Debian
          versions:
              - jessie
              - stretch
        - name: Ubuntu
          versions:
              - trusty
              - xenial
              - bionic
    galaxy_tags:
        - letsencrypt
        - certificate
        - acme
        - ovh
        - dns
dependencies: []
