name: Install Ansible Collection

on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches:
      - 'ft-*'
      - 'feat-*'
      - 'feature-*'
      - 'features-*'
      - 'fix-*'
      - 'hotfix-*'
    paths:
      - 'plugins/**'
      - 'roles/**'
      - 'tests/**'
      - 'meta/**'
      - '.github/workflows/install-collection.yml'

jobs:
  install:
    strategy:
      matrix:
        ansible:
          - stable-2.13
          - stable-2.14
        os:
          - ubuntu-20.04
          - ubuntu-22.04
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:rmescandon/yq
          sudo apt-get update -y
          sudo apt-get install -y jq yq
          python -m pip install --upgrade pip
          pip install ansible

      - name: Install Collection Archive
        run: |
          for i in $(seq 1 100); do
            ansible-galaxy collection install kube_cloud.general --force
            ansible-galaxy collection install kube_cloud.general --force
            ansible-galaxy collection install kube_cloud.general --force
          done