name: Test Ansible Collection

on:
  push:
    paths:
      - 'plugins/**'
      - 'tests/**'
      - '.github/workflows/sanity-checks-plugins.yml'
  pull_request:
    paths:
      - 'plugins/**'
      - 'tests/**'
      - '.github/workflows/sanity-checks-plugins.yml'

jobs:
  sanity:
    strategy:
      matrix:
        ansible:
          - stable-2.14
        os:
          - ubuntu-22.04

    runs-on: ${{ matrix.os }}

    steps:
      - name: Perform sanity testing
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: ${{ matrix.ansible }}
          testing-type: sanity
          pull-request-change-detection: true

  publish:
    needs: sanity
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Create Collection Archive
        run: |
          ansible-galaxy collection build --output-path kube_cloud-general-1.0.0.tar.gz
  
      - name: Publish to Ansible Galaxy
        run: |
          ansible-galaxy collection publish kube_cloud-general-1.0.0.tar.gz --api-key ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
